Changing logging levels
argonne-lcf/dlio_benchmark pull request #222
Opened 2024-08-27 22:15 UTC by zhenghh04

2024-08-27 23:04 UTC, hariharan-devarajan requested changes
We should add error logging as an option for pure performance mode. 
For the final per metric we should use a different logging, which outputs PRINT messages to STDOUT and redirects to the dlio.log file. 

The other logging is optional from the benchmark.

2024-08-27 23:04 UTC, hariharan-devarajan commented on dlio_benchmark/common/enumerations.py
> +    WARN = "warn"
```suggestion
    WARN = "warn"
    ERROR = "error"
```

2024-08-28 00:30 UTC, hariharan-devarajan commented
@zhenghh04 Can we not print the file name and line number for info logging. We should only do that for debug logging. This will significantly reduce log size.

2024-09-03 19:09 UTC, zhenghh04 commented
@hariharan-devarajan , made the changes as you suggested. Please review it again.

2024-09-03 19:16 UTC, hariharan-devarajan requested changes
We are almost there. I see we have some code which got reverted from the mock logging.

2024-09-03 19:16 UTC, hariharan-devarajan commented on dlio_benchmark/utils/utility.py
> +        def __init__(self,  cat, name=None, epoch=None, step=None, image_idx=None, image_size=None):
We should be reverting these changes.

2024-09-03 19:16 UTC, hariharan-devarajan commented on dlio_benchmark/utils/utility.py
> +        def update(self, epoch=None, step=None, image_idx=None, image_size=None, args={}):
Lets revert this

2024-09-03 19:16 UTC, hariharan-devarajan commented on dlio_benchmark/utils/utility.py
> +        def log_event(self, name, cat, start_time, duration, string_args=None):
Revert this

2024-09-03 19:17 UTC, zhenghh04 commented
@hariharan-devarajan , I am hesitating between using workflow.log_level to control the log level, vs using DLIO_LOG_LEVEL environment variable to control it. I slightly lean towards to the latter one, which is more common in other apps. What is your preference?

2024-09-03 19:37 UTC, hariharan-devarajan commented
> @hariharan-devarajan , I am hesitating between using workflow.log_level to control the log level, vs using DLIO_LOG_LEVEL environment variable to control it. I slightly lean towards to the latter one, which is more common in other apps. What is your preference?

I see a value in both. But I prefer the environment variable, too. By default, we should have WARN level, not info. Then we can make DLIO_LOG_LEVEL to higher logging levels like INFO and DEBUG.

We should switch the per epoch time to print and include the sample rate per epoch there.

Then, per step becomes info. 

And variable logging becomes debug.

2024-09-04 20:17 UTC, zhenghh04 commented
@hariharan-devarajan After reading the documentation more: https://docs.python.org/3/library/logging.html#levels, I feel that we should have default logging level to be info, and everything should go through logging, not through print. 

What do you think?

2024-09-04 20:59 UTC, hariharan-devarajan commented
So printing is different than logging in my opinion. 

The things that tell us about benchmark high-level like initialize, progress, and metrics. 

Logging here is for internal parts. 

I wrote a logger in the past on c++ in which I added print as the highest log above error. 

For benchmarks I feel it makes sense to have this.

2025-02-11 00:21 UTC, zhenghh04 commented
@hariharan-devarajan How about we just keep the logging system as this PR? We can have another PR to improve it? 

I need this feature for now to have an easy way to reduce some I/O overhead from the logging.

2025-02-11 15:31 UTC, zhenghh04 commented on dlio_benchmark/utils/utility.py
> +        def update(self, epoch=None, step=None, image_idx=None, image_size=None, args={}):
Forgot to response this: 

I tried (**kwargs) does not work. So I revert it back.

2025-02-14 05:49 UTC, zhenghh04 commented
> We should add error logging as an option for pure performance mode. For the final per metric we should use a different logging, which outputs PRINT messages to STDOUT and redirects to the dlio.log file.
> 
> The other logging is optional from the benchmark.

Now it is doing that

2025-02-14 05:52 UTC, zhenghh04 commented
> @zhenghh04 Can we not print the file name and line number for info logging. We should only do that for debug logging. This will significantly reduce log size.

This is done!

2025-02-14 06:06 UTC, zhenghh04 commented
> Now if u want to use logging for printing, I would create two loggers. One for printing and one for logging internal stuff.
> 
> The printing could always be info, internal, and cannot change by benchmark parameters.

Done!

2025-02-24 18:20 UTC, hariharan-devarajan requested changes
The documentation still refers to debug in workflow.

The rest looks good. 

https://github.com/search?q=repo%3Aargonne-lcf%2Fdlio_benchmark+debug+path%3A*.rst&type=code

2025-02-24 21:23 UTC, zhenghh04 commented
> The documentation still refers to debug in workflow.
> 
> The rest looks good.
> 
> https://github.com/search?q=repo%3Aargonne-lcf%2Fdlio_benchmark+debug+path%3A*.rst&type=code

Just fixed this.

2025-02-24 22:00 UTC, hariharan-devarajan approved these changes
Looks good.

2025-02-24 22:05 UTC, merged